version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    networks:
      - container-net
    depends_on:
      - mitm
    ports:
      - "3000:3000"

  mitm:
    build:
      context: ./proxy
    volumes:
      - ./proxy/scripts:/scripts
    ports:
      - "8091:8091"  # Proxy port
      - "8092:8092"  # Web interface
    networks:
      - container-net

  backend:
    build:
      context: ./backend
    networks:
      - container-net
    ports:
      - "5100:5100"  # Web interface

networks:
  container-net:
    driver: bridge

volumes:
  mitm_logs:
