
services:
  consumer:
    build:
      context: ./consumer
    networks:
      - container-net
    depends_on:
      - mitm
    ports:
      - "3000:3000"

  mitm:
    build:
      context: ./proxy
    volumes:
      - ./proxy:/proxy
    ports:
      - "8091:8091"  # Proxy port
    networks:
      - container-net

  backend:
    build:
      context: ./backend
    networks:
      - container-net
    ports:
      - "5100:5100"  # Web interface
  llm:
    build:
      context: ./llm
    networks:
      - container-net
    ports:
      - "5000:5000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mitm

networks:
  container-net:
    driver: bridge
