services:
  mitm:
    build:
      context: ./mitm
    volumes:
      - ./mitm:/mitm
    ports:
      - "8091:8091" # Proxy port
    networks:
      - container-net
  
  llm:
    build:
      context: ./llm
    volumes:
        - ./llm:/llm 
    ports:
      - "6000:6000"
    networks:
      - container-net

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    networks:
      - container-net
    ports:
      - "5100:5100" # Web interface


networks:
  container-net:
    driver: bridge
